environment:

  ANDROID_HOME: "C:\\android-sdk-windows"

  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"


clone_folder: "C:\\projects\\tiny-scanner-app"


init:

  - appveyor DownloadFile http://dl.google.com/android/android-sdk_r24.4.1-windows.zip

  - 7z x android-sdk_r24.4.1-windows.zip > nul

clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

install:

  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t tools

  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t platform-tools

  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-25.0.0

  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t android-25

  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-google-m2repository

  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-android-m2repository

before_build:
  - cd C:\projects\tiny-scanner-app\source\TinyScanner

build_script:

  - gradlew.bat clean testDebug jacocoDebugReport -Dscan --configure-on-demand --parallel --stacktrace



artifacts:

  - path: "build\\reports\\"



cache:

  - "%USERPROFILE%\\.m2"

  - "%USERPROFILE%\\.gradle"